# Built with Jekyll 3.2.0

# Setup
title:               "How Beautiful The World Is"
tagline:             'Anglo-American Travelers in Europe, 1880-1910'
description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://elotroalex.github.io'
baseurl:             '/baldwin'

# About/contact
author:
  name:              Meredith Levin
  url:               https://twitter.com/mjl361
  email:             mjl2209@columbia.edu
  
  
# DO NOT TOUCH ANYTHING BELOW THIS LINE
# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


